name: 'Build Tauri App on Windows'
on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-on-windows:
    runs-on: windows-latest # 使用微软提供的Windows环境

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc

    - name: Install dependencies (Windows)
      run: |
        choco install -y vcredist2022 webview2

    - name: Build the application
      run: cargo tauri build --target x86_64-pc-windows-msvc --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Tauri-Windows-Build
        path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/
